# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
import index


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(372, 226)
        Form.setFixedSize(Form.width(), Form.height())
        self.label = QLabel(Form)
        self.label.setGeometry(QRect(160, 20, 71, 21))
        self.label.setStyleSheet("font: 11pt \"Arial Black\";\n"
                                 "")
        self.label.setObjectName("label")
        self.pushButton = QPushButton(Form)
        self.pushButton.setGeometry(QRect(100, 150, 181, 31))
        self.pushButton.setObjectName("pushButton")
        self.widget = QWidget(Form)
        self.widget.setGeometry(QRect(50, 60, 241, 22))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.widget1 = QWidget(Form)
        self.widget1.setGeometry(QRect(50, 100, 241, 22))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QLabel(self.widget1)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QLineEdit(self.widget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)

        self.retranslateUi(Form)
        QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "用户登录"))
        self.label.setText(_translate("Form", "用户登录"))
        self.pushButton.setText(_translate("Form", "登录"))
        self.label_2.setText(_translate("Form", "用户名："))
        self.label_3.setText(_translate("Form", "密码：  "))


class Main(QDialog, Ui_Form):
    def __init__(self):
        super(Main, self).__init__()

        self.setupUi(self)
        self.setWindowTitle('成绩管理系统')
        self.pushButton.clicked.connect(self.login)

    def login(self):
        account = self.lineEdit.text()
        pwd = self.lineEdit_2.text()
        self.close()
        self.index_ui = index.Index()
        self.index_ui.show()

        '''if account == '123' and pwd == '123':
            self.close()
            self.index_ui = index.Index()
            self.index_ui.show()
        else:
            QMessageBox.critical(self, '警告', '密码或账号错误', QMessageBox.Yes)'''


if __name__ == '__main__':
    import sys

    v_compare = QVersionNumber(5, 6, 0)

    v_current, _ = QVersionNumber.fromString(QT_VERSION_STR)  # 获取当前Qt版本

    if QVersionNumber.compare(v_current, v_compare) >= 0:

        QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)  # Qt从5.6.0开始，支持High-DPI

        app = QApplication(sys.argv)  #

    else:

        app = QApplication(sys.argv)

        font = QFont("宋体")

        pointsize = font.pointSize()

        font.setPixelSize(pointsize * 90 / 72)

        app.setFont(font)


    # app = QApplication(sys.argv)

    main = Main()
    main.show()

    sys.exit(app.exec_())
